### ISSUE TITLE
PTZ Camera node misbehaves when more than one Network is defined? 

### ISSUE THREAD

**Issue by kb1ca** [haydendonald/node-red-contrib-ptzoptics#1]
I've been tinkering with this node to great success. However, when I add a second PTZ Camera node and define a second network configuration things go wrong. It feels like a fairly trivial bug somewhere but, unfortunately, the cause isn't immediately obvious to me.

To reproduce:
 - deploy a ptz-ptz node to a blank project and wire it up to send the camera a 'recall' command. Add a ptz-network named 'A' for an existing camera 192.168.1.1 Run tcpdump on the node.js host and observe that the packets are correctly exchanged with 192.168.1.1
- now add a second ptz-network config named 'B' for a second device at 192.168.1.2, but leave the original config 'A' selected. Deploy the update - the node-red console correctly warns the ptz-network node 'B' is unused. Inject the 'recall' and observe that tcpdump shows packets are now incorrectly being exchanged with 192.168.1.2
- deploying additional ptz-network configs results in the ptz-ptz node always using the most recently added config, regardless of which one is actively selected. The node-red console correctly warns that the ptz-network nodes that are not currently selected in the ptz-ptz node are unused when deploying updates.

Additionally, if more ptz-ptz node are added in the same or other flows, and a different ptz-network is selected in each, all instances incorrectly send their packets to the most recently added ptz-network config. If multiple ptz-ptz nodes attempt to send commands at the same time (eg. to coordinate moves across multiple cameras) the camera actually receiving the overlapping commands gets very upset...

**Comment by haydendonald** [comment]
Hi thanks for letting me know about this! I'll have a look at it as soon as i can! It may be caused by the network nodes being somehow overlapped..

**Comment by haydendonald** [comment]
Hi @kb1ca i have pushed an update which should fix this issue. As i don't have two cameras handy to test this could you please test it and tell me your results. Thankyou :)
